### ISSUE TITLE
Comparison tooltips appear funky

### ISSUE THREAD

**Issue by LWTechGaming** [BeMacized/GrimoireWeb#2]
When moving the mouse quickly between some tooltip-enabled comparison table items, the previous one appears to hang around for roughly half a second before disappearing. This causes overlaps, and while it's minor, it's a bit annoying.

GIF of what happens:
![Tooltips](http://images.lwtechgaming.me/itu7CLZ.gif)

**Comment by BeMacized** [comment]
This is default behaviour in Reactstrap for Uncontrolled tooltips. Unless I manually manage the state for each and every tooltip separately to replace the uncontrolled tooltips, this is not going to change.

**Comment by LWTechGaming** [comment]
I see. Cheers 👍
